language: python

sudo: false

matrix:
  include:
    - os: linux
      compiler: gcc
      addons: &gcc49
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++']
      env:
        - CXX='g++'

install:
  - pip install -r requirements.txt

script:
  - ./setup
  - cd build
  - make
  - cd ..
  - FLANDERS_BUILD_DIR=$PWD/build PYTHONPATH=$PWD/src py.test -s -vv test.py

notifications:
  email: false
