language: python

sudo: false

matrix:
  include:
    - os: linux
      python: 2.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      env:
        - CXX='g++-4.9'
    - os: linux
      python: 3.6
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      env:
        - CXX='g++-4.9'

install:
  - pip install -r requirements.txt

script:
  - cmake -H. -Bbuild -DENABLE_OPENMP=True -DCMAKE_CXX_COMPILER=$CXX
  - cd build
  - cmake --build .
# - ctest
  - cd ..
  - FLANDERS_BUILD_DIR=$PWD/build py.test -s -vv test.py

after_success:
  - pip install git+https://github.com/bast/flanders.git

notifications:
  email: false
