[package]
name = "flanders"
version = "0.2.0"
authors = ["Radovan Bast <bast@users.noreply.github.com>"]
edition = "2018"
readme = "README.md"

[lib]
name = "flanders"
crate-type = ["cdylib", "rlib"]

[package.metadata.maturin]
requires-python = ">=3.6"
classifier = ["Programming Language :: Python"]

[dependencies]
rand = "0.8.3"
rayon = "1.5.0"
pyo3 = { version = "0.13", features = ["extension-module"] }
